name: Docker Compose Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create env file
      run: |
        cd /home/runner/work/acg-flask-web-app/acg-flask-web-app
        touch .env
        echo "${{ secrets.SERVER_ENV_PROD }}" > .env
    
    - name: SCP Upload
      uses: betanzos/scp-upload@v1
      with:
        source: /home/runner/work/acg-flask-web-app/acg-flask-web-app
        host: ${{ secrets.HOST }}
        username: jenkins
        key: ${{ secrets.PRIVATE_KEY }}
        remote_dir: ~/workspace
        recursive: true
    
    - name: Run Docker Compose Up (SSH)
      run: |
        ssh jenkins@${{ secrets.HOST }}
        cd ~/workspace
        docker compose down --remove-orphans
        docker compose -d --build
        docker ps

