name: Docker Compose Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create env file
      run: |
        touch .env
        echo "${{ secrets.SERVER_ENV_PROD }}" > .env
    
    - name: Docker-compose Deployment
      uses: Autom3/docker-deployment-action@3.0.1
      with:
        # Remote Docker host ie (user@host)
        remote_docker_host: ${{ secrets.HOST }}
        ssh_public_key: ${{ secrets.PUBLIC_KEY }}
        ssh_private_key: ${{ secrets.PRIVATE_KEY }}
        args: docker compose up -d --build
        stack_file_name: docker-compose.yml
        docker_prune: 1
